# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  # 16.04 LTS
  config.vm.box = "ubuntu/xenial64" 

  config.vm.network :private_network, ip: "192.168.68.8"

  config.vm.provision "ansible_local" do |ansible|
    ansible.playbook = "apps/build/playbook.yml"
  end
end
