language: elixir
elixir: 1.4.5
otp_release: 20.0
sudo: required

services:
  - docker

before_script:
  - sudo service postgresql stop
  - docker-compose up -d
  - docker ps -a
  - MIX_ENV=test mix compile

script:
  - mix test

after_script:
  - docker-compose down
