language: elixir
elixir: 1.3.1
otp_release: 18
addons:
  postgresql: 9.4
before_script:
  - MIX_ENV=test mix compile
  - MIX_ENV=test mix ecto.create
script:
  - mix test
  - echo "Run for each app" ; for app in apps/**; do cd $app && mix test; cd ../.. ; done
